# Generated by Django 5.2.5 on 2025-08-08 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='hobby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.hobby'),
            preserve_default=False,
        ),
    ]
