# Generated by Django 5.2.5 on 2025-08-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_craft_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craft',
            name='hobby',
        ),
        migrations.AddField(
            model_name='craft',
            name='hobby',
            field=models.ManyToManyField(to='main_app.hobby'),
        ),
    ]
