# Generated by Django 5.2.5 on 2025-08-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_craft_hobby_craft_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craft',
            name='hobby',
        ),
    ]
