# Generated by Django 5.2.5 on 2025-08-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_craft_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='hobby',
            field=models.ManyToManyField(to='main_app.hobby'),
        ),
    ]
