# Generated by Django 5.2.5 on 2025-08-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_craft_hobby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='craft',
            old_name='hobby',
            new_name='hobbies',
        ),
    ]
